### ISSUE TITLE
Central place to configure widgets active and its endpoints

### ISSUE THREAD

**Issue by thelinuxlich** [mattbrailsford/vuepoint#3]
Is it on your roadmap?

**Comment by mattbrailsford** [comment]
I'm not sure I know what you mean. Could you expand your thinking a little?

Matt

**Comment by thelinuxlich** [comment]
I mean, to use the different chart types as components, maybe passing the http data endpoint as a prop

**Comment by mattbrailsford** [comment]
It's not currently in my roadplan. My aim is just to make a bunch of small re-usable components to create a dashboard from. As a developer you can then make your own components from those building blocks that are specific to your needs / data if that makes sense?

**Comment by biapar** [comment]
It's possible to use a JSON file like vudash or https://github.com/xmodulus/mdash
